name: Build and Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Docker Repository
      uses: HurricanKai/Publish-Docker-Github-Action@master
      if: contains(github.ref, 'refs/tags/v')
      with:
        name: kheekdotcom/clamav-docker
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
